import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar'
import BottomNav from './components/BottomNav'
import localFont from 'next/font/local'

const poppins = localFont({
  src: './fonts/Poppins-Regular.ttf', // Path must be relative to this layout.jsx file
  display:'swap',
  variable: '--font-poppins'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); // Fixed: Removed the stray '2' here

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* Added 'font-roboto' to the body class below */}
      <body className="relative font-roboto px-4 max-sm:px-2 min-h-full overflow-hidden h-screen">
          <Navbar/>
          {children}
          <BottomNav/>
      </body>
    </html>
  );
}
